[package]
name = "big-calc"
version = "0.1.0"
edition = "2024"

[dependencies]
add_1 = { path = "add/add_1" }
add_2 = { path = "add/add_2" }
add_3 = { path = "add/add_3" }
add_4 = { path = "add/add_4" }
add_5 = { path = "add/add_5" }
add_6 = { path = "add/add_6" }
add_7 = { path = "add/add_7" }
add_8 = { path = "add/add_8" }
subtract_1 = { path = "subtract/subtract_1" }
subtract_2 = { path = "subtract/subtract_2" }
subtract_3 = { path = "subtract/subtract_3" }
subtract_4 = { path = "subtract/subtract_4" }
subtract_5 = { path = "subtract/subtract_5" }
subtract_6 = { path = "subtract/subtract_6" }
subtract_7 = { path = "subtract/subtract_7" }
subtract_8 = { path = "subtract/subtract_8" }
multiply_1 = { path = "multiply/multiply_1" }
multiply_2 = { path = "multiply/multiply_2" }
multiply_3 = { path = "multiply/multiply_3" }
multiply_4 = { path = "multiply/multiply_4" }
multiply_5 = { path = "multiply/multiply_5" }
multiply_6 = { path = "multiply/multiply_6" }
multiply_7 = { path = "multiply/multiply_7" }
multiply_8 = { path = "multiply/multiply_8" }
divide_1 = { path = "divide/divide_1" }
divide_2 = { path = "divide/divide_2" }
divide_3 = { path = "divide/divide_3" }
divide_4 = { path = "divide/divide_4" }
divide_5 = { path = "divide/divide_5" }
divide_6 = { path = "divide/divide_6" }
divide_7 = { path = "divide/divide_7" }
divide_8 = { path = "divide/divide_8" }
square_1 = { path = "square/square_1" }
square_2 = { path = "square/square_2" }
square_3 = { path = "square/square_3" }
square_4 = { path = "square/square_4" }
square_5 = { path = "square/square_5" }
square_6 = { path = "square/square_6" }
square_7 = { path = "square/square_7" }
square_8 = { path = "square/square_8" }
square_root_1 = { path = "square_root/square_root_1" }
square_root_2 = { path = "square_root/square_root_2" }
square_root_3 = { path = "square_root/square_root_3" }
square_root_4 = { path = "square_root/square_root_4" }
square_root_5 = { path = "square_root/square_root_5" }
square_root_6 = { path = "square_root/square_root_6" }
square_root_7 = { path = "square_root/square_root_7" }
square_root_8 = { path = "square_root/square_root_8" }
numbers_1 = { path = "numbers/numbers_1" }
numbers_2 = { path = "numbers/numbers_2" }
numbers_3 = { path = "numbers/numbers_3" }
numbers_4 = { path = "numbers/numbers_4" }
numbers_5 = { path = "numbers/numbers_5" }
numbers_6 = { path = "numbers/numbers_6" }
numbers_7 = { path = "numbers/numbers_7" }

[workspace]
members = ["add/*", "subtract/*", "multiply/*", "divide/*", "square/*", "square_root/*", "numbers/*"]
